### ISSUE TITLE
install with yarn on void linux musl

### ISSUE THREAD

**Issue by gasacchi** [purescript/npm-installer#30]
## Description

I want to try purescript, and try to install on my void linux musl with yarn and get error instead

## To Reproduce

Steps to reproduce the behavior.
```
yarn global add purescript
```
output:
```
Command: install-purescript --purs-ver=0.13.8
Arguments: 
Directory: /home/gasacchi/.config/yarn/global/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.8 binary is provided for linux (4s)
[ SUCCESS ] Download the prebuilt PureScript binary (55s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/gasacchi/xxx/.dev/gsclinux/.config/yarn/global/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

↓ Fallback: building from source

[ FAILURE ] Check if 'stack' command is available
Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user --numeric-version
spawn stack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
## Expected behavior

purescript success installed
## Additional context

running on Void linux with musl libc
## PureScript version

0.13.8

**Comment by hdgarrood** [comment]
I think there are a couple of separate issues here:

- I'm 99% sure that the ENOENT you're seeing is due to the `purs` binary looking for a libc.so to dynamically link with and not finding one. We can improve this error with the approach described in #22 
- stack doesn't appear to work very well on void linux. This isn't something we can really do anything about here unfortunately; you might consider reporting an issue on https://github.com/commercialhaskell/stack

Since the only issue concerning purescript is the ENOENT error message, and we already have an issue for that, I'm going to close this. Sorry I couldn't be more help.
